config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  
  resources :tops
  resources :houses
  resources :sessions, only: [:new,:create,:show]
  resources :users
  resources :owners, only: [:new, :create]
  resources :contacts
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true,length: { maximum: 30 }
    validates :email, presence: true,length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
           
end

app/models/house.rb
class House < ApplicationRecord
    belongs_to :owner
    mount_uploader :image, ImageUploader
    
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_many :houses
    validates :name, presence: true,length: { maximum: 255 }
    # validates :phone_number, presence: true,length: { maximum: 255 }
    validates :email, presence: true,length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
            before_validation { email.downcase! }
    has_secure_password
    validates :password,presence: true,length:{ minimum:4 }
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true,length: { maximum: 30 }
    validates :email, presence: true,length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
            before_validation { email.downcase! }
    has_secure_password
    validates :password,presence: true,length:{ minimum:4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
  
    def create
        @contact = Contact.new(contact_params)
        #@house.owner_id = current_owner.id
        #respond_to do |format|
            if @contact.save
                ContactMailer.contact_mail(@contact).deliver  ##追記
                redirect_to houses_path
            else
                render :new
            end
        #end
    end
    
    private
    
    def contact_params
        params.require(:contact).permit(:name,:email,:content)
    end 
  
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :false_user, only:[:edit, :destroy]
  def index
    words = params[:q].delete(:search_words) if params[:q].present?
  if words.present?
    params[:q][:groupings] = []
    words.split(/[ 　]/).each_with_index do |word, i| #全角空白と半角空白で切って、単語ごとに処理します
      params[:q][:groupings][i] = { name_or_address_or_station_cont: word }
    end
  end
    #@houses = House.all
    @search = House.ransack(params[:q])
    @houses = @search.result(distinct: true)
    
  end
  
  def new
    @house = House.new
  end
  
  def create
    @house = House.new(house_params)
    @house.owner_id = current_owner.id
    if @house.save
      redirect_to houses_path
    else
      render 'new'
    end
  end
  
  def show
    @house = House.find(params[:id])
    @price = Price.find_by(adress: @house.adress)
  end
  
  def edit
    @house = House.find(params[:id])
  end
  
  def update
    @house = House.find(params[:id])
    if @house.update(house_params)
      redirect_to houses_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @house = House.find(params[:id])
    @house.destroy
    redirect_to houses_path
  end

  private
  
  def house_params
    params.require(:house).permit(:name,:station,:deposit,:key,:floor,:money,:comment,:adress, [:image])
  end 
  def false_user
    if current_user.id == @picture.user_id
      #redirect_to new_session_path
    
    else
      redirect_to new_session_path
    end
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
    def new
        @owner = Owner.new
    end
    
    def create
        @owner = Owner.new(owner_params)
        if @owner.save
            
            redirect_to houses_path
        else
            render 'new'
        end
    end
    
    def show
        @owner = Owner.find(params[:id])
    end
    
    private
    
    def owner_params
        params.require(:owner).permit(:name, :email, :phone_number, :adress, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    if session[:email] == Owner.find_by(email:session[:email])
      owner = Owner.find_by(email: params[:session][:email].downcase)
      if owner && owner.authenticate(params[:session][:password])
        session[:owner_id] = owner.id
        redirect_to owners_path(owner.id)
        #redirect_to houses_path  
      else
        flash.now[:danger] = 'ログインに失敗しました'
        render 'new'
      end
    else
      user = Uer.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        #redirect_to owners_path(owner.id)
        redirect_to houses_path
      else
        flash.now[:danger] = 'ログインに失敗しました'
        render 'new'
      end
    end
  end
  
  def destroy
    session.delete(:owner_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
        else
            render 'new'
        end
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    private
    
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_owner
        @current_owner ||= Owner.find_by(id: session[:owner_id])
    end
    
    def logged_in?
        current_owner.present?
    end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/houses/edit.html.erb
<%= form_with(model: @house, local: true) do |form| %>
  <div class="house_title">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="house_title">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="house_title">
    <%= form.label :station%>
    <%= form.text_field :station %>
  </div>
  <div class="house_title"><!-- 敷金 -->
    <%= form.label :deposit %>
    <%= form.text_field :deposit %>
  </div>
  <div class="house_title"><!-- 礼金 -->
    <%= form.label :key %>
    <%= form.text_field :key %>
  </div>
  <div class="house_title">
    <%= form.label :floor %>
    <%= form.text_field :floor %>
  </div>
  <div class="house_title">
    <%= form.label :money %>
    <%= form.text_field :money %>
    
  </div>
  <div class="house_title">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>
  <div class="house_title">
    <%= form.label :adress %>
    <%= form.text_field :adress %>
  </div>
  <%= form.submit %>
<% end %>

app/views/houses/index.html.erb
<header>
    <ul>
        <li><%= link_to 'Home', '/houses' %></li>
        <li><%= link_to 'New',new_house_path %></li>
        <li><%#= link_to 'User', users_path(current_user.id) %></li>
        <li><%#= link_to 'Logout' , session_path(current_user.id),method: :delete %></li>
        
        
    </ul>
</header>

<div class="houses_index">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h2>物件一覧</h2>
        <%= search_form_for @search do |f| %>
  <div class="form-group">
    <%= f.label :name_cont, "Name" %>
    <%= f.text_field :name_cont, class: "form-control" %>
    <%= f.label :adress_cont, "Adress" %>
    <%= f.text_field :adress_cont, class: "form-control" %>
    <%= f.label :station_cont, "Station" %>
    <%= f.text_field :station_cont, class: "form-control" %>
    <%= f.label :floor_cont, "floor" %>
    <%= f.text_field :floor_cont, class: "form-control" %>
    <%= f.label :money_cont, "Money" %>
    <%= f.text_field :money_cont, class: "form-control" %>



  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>
        <% @houses.each do |house| %>
        <div class="">
            <h3><%= link_to house.name, house_path(house.id) %></h3>
            <p><%= image_tag house.image.url unless house.image.blank? %></p>
        </div>
        <%= link_to 'show', house_path(house.id) %>
        <%= link_to 'edit', edit_house_path(house.id) %>
        <%= link_to 'delete', house_path(house.id), method: :delete %>
        <% end %>
    </div>
    
    <div class="col-md-3"></div>
</div>

<!--
<footer>
    <p>@Copyright.2018.12</p>
</footer>
-->

app/views/houses/new.html.erb
<%= form_with(model: @house, local: true) do |form| %>
  <div class="house_title">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="house_title">
    <%#= form.label :image %>
    <%#= form.file_field :image, :multiple => true %>
    <%= form_for(@house) do |f| %>
      <%= f.fields_for :images do |iamge| %>
      <%= f.file_field :image, :multiple => true %>
    <% end %>
  </div>
  <div class="house_title">
    <%= form.label :station%>
    <%= form.text_field :station %>
  </div>
  <div class="house_title"><!-- 敷金 -->
    <%= form.label :deposit %>
    <%= form.text_field :deposit %>
  </div>
  <div class="house_title"><!-- 礼金 -->
    <%= form.label :key %>
    <%= form.text_field :key %>
  </div>
  <div class="house_title">
    <%= form.label :floor %>
    <%= form.text_field :floor %>
  </div>
  <div class="house_title">
    <%= form.label :money %>
    <%= form.text_field :money %>
    
  </div>
  <div class="house_title">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>
  <div class="house_title">
    <%= form.label :adress %>
    <%= form.text_field :adress %>
  </div>
  <%= form.submit %>
<% end %>
<% end %>

app/views/houses/show.html.erb
<div class="house_show">
    <div class="a">
        <h2><%= @house.name %></h2>
        <% if @house.image? %>
        <p><%= image_tag @house.image.url %></p>
        <% end %>
        <p>家賃：月<%= @house.money %>円</p>
        <p>敷金/礼金：<%= @house.deposit %>円/<%= @house.key %>円</p>
        <p>最寄り駅：<%= @house.station %></p>
        <p>間取り：<%= @house.floor %></p>
        <p>住所：<%= @house.adress %></p>

    </div>
    <div class="comparision">
        <p><%= @house.adress %>の相場：<%= @price.money %></p>
        <p>この物件の家賃：<%= @house.money %></p>
        
    </div>
    
    <div class="home_contact">
    <%= form_with(model: @contact, local: true, url: contacts_path) do |form| %>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :contact_name %>
      </div>
    
      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email, id: :contact_email %>
      </div>
    
      <div class="field">
        <%= form.label :content %>
        <%= form.text_area :content, id: :contact_content %>
      </div>
    
      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>

    </div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/owners/new.html.erb
<header>
    <ul>
        <li><%= link_to 'Home', '/houses' %></li>
        <li><%#= link_to 'User', users_path(current_user.id) %></li>
        <li><%#=# link_to 'Logout', users_path(current_user.id) %></li>
        
        
    </ul>
</header>
<h1>Sign up</h1>
<% if @owner.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this @owner from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @owner, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>
  
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  
  <%= f.label :adress %>
  <%= f.text_field :adress %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/owners/show.html.erb
<header>
    <ul>
        <li><%= link_to 'Home', '/houses' %></li>
        <li><%#= link_to 'User', users_path(current_user.id) %></li>
        <li><%= link_to 'Logout' , session_path(current_owner.id),method: :delete %></li>
        
        
    </ul>
</header>
<h1><%= @owner.name %>のページ</h1>

<p>メールアドレス: <%= @owner.email %></p>

<table>    
    <tr>
        <% @owner.houses.each do |house| %>
        <td class="user_pic_img"><%= link_to image_tag(house.image.url),picture_path(house.id) %></td>
        <% end %>
        </tr>
    <br >
</table>

app/views/tops/index.html.erb
<body id="top">
    <div class="tops">
        <div class="top_content">
            <p>地方から都心へ...！</p>
            <p>都心に住んだらやりたいことたくさん！</p>
            <p>その前に，お気に入りの家を見つけて自分だけの部屋を作りましょう．</p>
            
            <button class="top_btn"><%= link_to 'Start', '/users/new' %></button>
            
        </div>
        <div class="top_fot">
            <p>不動産会社の方はこちらから<%= link_to 'Login', '/owners/new' %></p>
        </div>
    </div>
</body>

app/views/users/new.html.erb
<header>
    <ul>
        <li><%= link_to 'Home', '/houses' %></li>
        <li><%#= link_to 'User', users_path(current_user.id) %></li>
        <li><%#=# link_to 'Logout', users_path(current_user.id) %></li>
        
        
    </ul>
</header>
<div class="user_new">
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>
</div>

app/views/users/show.html.erb
<header>
    <ul>
        <li><%= link_to 'Home', '/houses' %></li>
        <li><%#= link_to 'User', users_path %></li>
        
    </ul>
</header>

<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>